/**
 * Rank.
 */
const enum Rank {
	TWELFTH = "TWELFTH",
	ELEVENTH = "ELEVENTH",
	TENTH = "TENTH",
	NINTH = "NINTH",
	EIGHTH = "EIGHTH",
	SEVENTH = "SEVENTH",
	SIXTH = "SIXTH",
	FIFTH = "FIFTH",
	FOURTH = "FOURTH",
	THIRD = "THIRD",
	SECOND = "SECOND",
	FIRST = "FIRST"
}