/**
 * Theme.
 */
const enum Theme {
	ANNEES_60 = "ANNEES_60",
	ANNEES_70 = "ANNEES_70",
	ANNEES_80 = "ANNEES_80",
	ANNEES_90 = "ANNEES_90",
	ANNEES_2000 = "ANNEES_2000",
	CINEMAS = "CINEMAS",
	SERIES = "SERIES",
	DISNEY = "DISNEY",
	CLASSIQUES = "CLASSIQUES"
}